import type { TileDefinition } from '../types/tile.ts'
import { ABBOT_C3_GARDEN_TILES } from './abbotGardenTilesC3.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: base-c3
 */
export const BASE3_TILES: TileDefinition[] = [
  {
    "id": "base3_A",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_A.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L55,100 L56,91 L81,84 L73,62 L74,41 L50,28 L44,9 L32,9 L18,57 L64,74 L45,87 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 25
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M64,62 L73,70 L74,80 L65,85 L50,90 L50,100",
        "meepleCentroid": {
          "x": 51,
          "y": 88
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M30,30 L70,30 L70,70 L30,70 Z",
        "meepleCentroid": {
          "x": 46,
          "y": 51
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "road0",
        "cloister0"
      ],
      [
        "cloister0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_B",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_B.png",
    "count": 4,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 25
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M30,30 L70,30 L70,70 L30,70 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "cloister0"
      ]
    ]
  },
  {
    "id": "base3_C",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_C.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city0"
    }
  },
  {
    "id": "base3_D",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_D.png",
    "count": 4,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L66,42 L30,56 L0,49",
        "meepleCentroid": {
          "x": 52,
          "y": 47
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,53 L31,62 L66,48 L100,56 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 80
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L31,26 L52,30 L71,25 L100,0 L100,44 L69,37 L28,50 L0,44 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 37
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "startingTile": true,
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_E",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_E.png",
    "count": 4,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L73,41 L35,57 L32,37 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M35,57 L73,40 L100,0 L100,100 L0,100 L0,0 L32,37 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 71
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_F",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_F.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L30,25 L50,30 L70,25 L100,0 L100,100 L78,82 L59,82 L37,78 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L70,26 L50,30 L30,26 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 17
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,100 L100,100 L78,81 L59,82 L37,78 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_G",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_G.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L30,25 L50,30 L70,25 L100,0 L100,100 L73,81 L56,82 L31,81 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L70,25 L50,31 L29,25 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 25
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,100 L100,100 L74,81 L58,82 L31,80 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "field0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_H",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_H.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L67,22 L66,33 L26,31 L0,0 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 15
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,100 L0,100 L100,100 L67,72 L19,77 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 85
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L0,100 L19,77 L44,74 L67,72 L100,100 L100,0 L66,22 L66,33 L26,31 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "field0",
        "city1"
      ]
    ]
  },
  {
    "id": "base3_I",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_I.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L0,100 L23,79 L29,47 L24,24 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 47
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L78,22 L50,23 L36,25 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 14
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M78,22 L100,0 L100,100 L0,100 L23,79 L29,47 L27,36 L24,24 L0,0 L36,25 L50,22 Z",
        "meepleCentroid": {
          "x": 60,
          "y": 60
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city1",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city1",
        "field0"
      ],
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "base3_J",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_J.png",
    "count": 3,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L0,0 L30,30 L68,26 L74,17 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 14
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L74,46 L67,56 L52,61 L47,80 L50,100",
        "meepleCentroid": {
          "x": 56,
          "y": 60
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L30,30 L69,26 L74,16 L100,0 L100,48 L78,43 L64,52 L50,58 L41,77 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 56
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M100,50 L76,53 L59,62 L53,79 L54,100 L100,100 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "base3_K",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_K.png",
    "count": 3,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L75,38 L49,36 L29,28 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L40,45 L61,59 L61,69 L51,79 L49,100",
        "meepleCentroid": {
          "x": 53,
          "y": 52
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L29,28 L48,35 L74,39 L100,0 L100,100 L55,100 L57,81 L68,71 L67,56 L42,41 L0,44 Z",
        "meepleCentroid": {
          "x": 82,
          "y": 54
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L40,52 L53,61 L53,67 L44,78 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_L",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_L.png",
    "count": 3,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 13
        }
      },
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M100,49 L87,51 L74,52",
        "meepleCentroid": {
          "x": 83,
          "y": 51
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M50,100 L53,84 L60,70",
        "meepleCentroid": {
          "x": 55,
          "y": 78
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M0,49 L13,51 L22,54 L34,54",
        "meepleCentroid": {
          "x": 19,
          "y": 53
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M71,61 L100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 77
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L47,64 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 78
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,0 L30,26 L52,30 L72,25 L100,0 L100,43 L0,43 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 37
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field2",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field2",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "city0",
        "field2"
      ],
      [
        "road_w",
        "field2"
      ],
      [
        "road_e",
        "field2"
      ],
      [
        "road_e",
        "field0"
      ],
      [
        "road_s",
        "field0"
      ],
      [
        "road_s",
        "field1"
      ],
      [
        "road_w",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_M",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_M.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M61,58 L20,37 L0,0 L100,0 L100,100 L80,77 L60,71 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 67,
          "y": 29
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M20,38 L61,58 L61,72 L80,77 L100,100 L0,100 L0,0 Z",
        "meepleCentroid": {
          "x": 33,
          "y": 69
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_N",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_N.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M63,60 L18,35 L0,0 L100,0 L100,100 L82,78 L61,71 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 30
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M18,36 L62,60 L60,71 L81,78 L100,100 L0,100 L0,0 Z",
        "meepleCentroid": {
          "x": 32,
          "y": 69
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_O",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_O.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L79,25 L78,41 L22,72 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 32,
          "y": 29
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L85,50 L72,57 L68,68 L51,73 L44,79 L50,100",
        "meepleCentroid": {
          "x": 58,
          "y": 71
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M50,79 L70,75 L80,58 L100,53 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 77
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M22,73 L79,41 L79,25 L100,0 L100,43 L79,45 L67,54 L62,65 L37,74 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 60,
          "y": 53
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_P",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_P.png",
    "count": 3,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L76,42 L50,58 L22,71 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 25
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L77,51 L67,71 L42,76 L49,90 L51,100",
        "meepleCentroid": {
          "x": 66,
          "y": 70
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M52,80 L72,75 L82,57 L100,55 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 82
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M22,72 L79,28 L100,0 L100,45 L79,41 L64,65 L47,69 L37,78 L44,92 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 57,
          "y": 62
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_Q",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_Q.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 49,
          "y": 29
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,76 L50,71 L70,75 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 80
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M35,78 L65,78 L65,95 L35,95 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 87
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "garden0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_R",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_R.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 31
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,75 L50,70 L71,75 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 80
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base3_S",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_S.png",
    "count": 2,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 51,
          "y": 30
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M51,68 L47,78 L50,87 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 82
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M33,74 L43,71 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 31,
          "y": 82
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M55,72 L67,74 L100,100 L55,100 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 82
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_T",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_T.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 33
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M51,71 L48,79 L51,89 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 83
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M29,77 L44,72 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 32,
          "y": 83
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M55,72 L72,76 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 68,
          "y": 83
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base3_U",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_U.png",
    "count": 7,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M49,0 L48,14 L42,26 L47,38 L40,52 L43,65 L54,75 L51,86 L51,100",
        "meepleCentroid": {
          "x": 42,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M58,80 L58,68 L47,54 L54,38 L48,26 L55,11 L55,0 L100,0 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 50
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L43,0 L44,9 L38,23 L42,37 L36,56 L41,69 L49,78 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field1",
        "road0"
      ]
    ]
  },
  {
    "id": "base3_V",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_V.png",
    "count": 8,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,51 L32,49 L41,54 L41,65 L50,72 L51,84 L50,100",
        "meepleCentroid": {
          "x": 41,
          "y": 57
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L54,100 L58,69 L48,61 L45,48 L27,43 L0,46 Z",
        "meepleCentroid": {
          "x": 65,
          "y": 36
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L32,55 L36,67 L44,75 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 23,
          "y": 74
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field1",
        "road0"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "base3_W",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_W.png",
    "count": 4,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M100,50 L85,50 L69,50",
        "meepleCentroid": {
          "x": 83,
          "y": 51
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M41,60 L37,71 L41,82 L49,88 L50,100",
        "meepleCentroid": {
          "x": 48,
          "y": 82
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M27,42 L16,48 L0,50",
        "meepleCentroid": {
          "x": 16,
          "y": 46
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,43 L80,44 L78,28 L43,19 L26,37 L0,46 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M54,84 L43,73 L48,62 L68,56 L100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 78,
          "y": 75
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,54 L25,56 L33,82 L41,88 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "field0",
        "road_w"
      ],
      [
        "field0",
        "road_e"
      ],
      [
        "field1",
        "road_e"
      ],
      [
        "field1",
        "road_s"
      ],
      [
        "field2",
        "road_s"
      ],
      [
        "field2",
        "road_w"
      ]
    ]
  },
  {
    "id": "base3_X",
    "imageUrl": "/images/BaseGame_C3/Base_Game_C3_Tile_X.png",
    "count": 1,
    "expansionId": "base-c3",
    "version": "C3",
    "segments": [
      {
        "id": "road_n",
        "type": "ROAD",
        "svgPath": "M50,0 L50,12 L56,25 L45,38",
        "meepleCentroid": {
          "x": 51,
          "y": 16
        }
      },
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M74,47 L89,49 L100,50",
        "meepleCentroid": {
          "x": 80,
          "y": 47
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M56,64 L45,75 L49,85 L49,100",
        "meepleCentroid": {
          "x": 48,
          "y": 84
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M29,54 L15,51 L0,51",
        "meepleCentroid": {
          "x": 15,
          "y": 51
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M54,0 L100,0 L100,46 L74,42 L70,31 L62,26 L57,12 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 16
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M54,85 L56,73 L80,80 L91,67 L86,54 L100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 84
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,54 L19,57 L32,61 L43,69 L39,76 L44,87 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 82
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L44,0 L46,16 L49,25 L36,39 L27,45 L0,46 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 17
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "road_n",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "field0",
        "road_e"
      ],
      [
        "field1",
        "road_e"
      ],
      [
        "field1",
        "road_s"
      ],
      [
        "field2",
        "road_s"
      ],
      [
        "field2",
        "road_w"
      ],
      [
        "field3",
        "road_w"
      ],
      [
        "field3",
        "road_n"
      ],
      [
        "field0",
        "road_n"
      ]
    ]
  },
  ...ABBOT_C3_GARDEN_TILES,
]
