import type { TileDefinition } from '../types/tile.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: base-c1
 */
export const BASE1_TILES: TileDefinition[] = [
  {
    "id": "base1_A",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_20.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 25
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M40,60 L35,67 L44,86 L47,100",
        "meepleCentroid": {
          "x": 42,
          "y": 82
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M43,23 L74,57 L64,68 L25,58 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "cloister0",
        "road0"
      ],
      [
        "cloister0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_B",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_19.jpg",
    "count": 4,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 25
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M35,14 L73,46 L42,66 L22,57 Z",
        "meepleCentroid": {
          "x": 44,
          "y": 44
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "cloister0"
      ]
    ]
  },
  {
    "id": "base1_C",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_01.jpg",
    "count": 1,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city0"
    }
  },
  {
    "id": "base1_D",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_16.jpg",
    "count": 4,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 15
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,46 L100,46 L100,54 L0,54 Z",
        "meepleCentroid": {
          "x": 57,
          "y": 40
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,54 L100,54 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 53,
          "y": 71
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,40 L46,40 L46,46 L0,46 Z",
        "meepleCentroid": {
          "x": 21,
          "y": 35
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "startingTile": true,
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_E",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_14.jpg",
    "count": 5,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 46,
          "y": 12
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,40 L50,50 L100,40 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 65
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_F",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_12.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L32,20 L79,18 L100,0 L100,100 L70,72 L53,78 L22,77 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L79,18 L33,21 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 13
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,100 L100,100 L69,71 L53,78 L21,77 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 87
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field1",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_G",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_13.jpg",
    "count": 1,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L0,0 L21,28 L18,53 L23,73 L0,100 L100,100 L81,76 L79,33 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M100,0 L100,100 L81,75 L81,35 Z",
        "meepleCentroid": {
          "x": 90,
          "y": 49
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L0,100 L24,74 L18,52 L21,28 Z",
        "meepleCentroid": {
          "x": 12,
          "y": 52
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_H",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_11.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L0,0 L26,24 L53,30 L77,19 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 14
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,100 L0,100 L14,75 L38,59 L67,61 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 82
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L27,25 L50,30 L79,18 L100,0 L100,100 L67,62 L38,59 L14,75 L0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 45
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "field0",
        "city1"
      ]
    ]
  },
  {
    "id": "base1_I",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_08.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L100,100 L69,60 L70,32 L74,19 Z",
        "meepleCentroid": {
          "x": 85,
          "y": 49
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L65,13 L40,20 Z",
        "meepleCentroid": {
          "x": 45,
          "y": 9
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L41,21 L68,12 L100,0 L74,19 L71,31 L69,60 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 41,
          "y": 56
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city1",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city1",
        "field0"
      ],
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "base1_J",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_17.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L0,0 L37,31 L59,30 L60,20 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 15
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,45 L61,46 L55,58 L44,69 L48,100",
        "meepleCentroid": {
          "x": 53,
          "y": 57
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L38,32 L60,30 L60,21 L100,0 L100,38 L60,41 L39,66 L39,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 54
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M50,72 L67,53 L100,50 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_K",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_15.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 13
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,49 L26,49 L38,67 L47,74 L47,100",
        "meepleCentroid": {
          "x": 35,
          "y": 61
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M54,46 L100,46 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 52
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L46,54 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 22,
          "y": 76
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_L",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_18.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L74,33 L45,35 L20,27 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 14
        }
      },
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M57,62 L85,51 L100,50",
        "meepleCentroid": {
          "x": 78,
          "y": 55
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M43,72 L42,85 L46,100",
        "meepleCentroid": {
          "x": 43,
          "y": 80
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M0,50 L21,52 L37,61",
        "meepleCentroid": {
          "x": 21,
          "y": 52
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M61,69 L100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 78,
          "y": 79
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L35,66 L39,100 L0,100 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 79
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,0 L21,29 L46,35 L75,33 L100,0 L100,44 L0,43 Z",
        "meepleCentroid": {
          "x": 47,
          "y": 42
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field2",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field2",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "road_e",
        "field0"
      ],
      [
        "road_s",
        "field0"
      ],
      [
        "road_s",
        "field1"
      ],
      [
        "road_w",
        "field1"
      ],
      [
        "field2",
        "road_s"
      ],
      [
        "road_e",
        "field2"
      ]
    ]
  },
  {
    "id": "base1_M",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_07.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L65,29 L33,49 L23,89 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 22,
          "y": 27
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M33,49 L65,30 L100,0 L100,100 L0,100 L23,89 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 66
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_N",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_06.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L70,25 L40,40 L30,75 Z",
        "meepleCentroid": {
          "x": 27,
          "y": 29
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M41,41 L73,23 L100,0 L100,100 L0,100 L30,75 Z",
        "meepleCentroid": {
          "x": 67,
          "y": 65
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_O",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_10.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L70,25 L40,40 L30,75 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 25,
          "y": 28
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,51 L83,53 L70,61 L64,74 L50,82 L46,100",
        "meepleCentroid": {
          "x": 66,
          "y": 71
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M69,77 L100,57 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 84
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M32,75 L44,47 L100,0 L99,46 L71,51 L43,79 L39,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 60
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_P",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_09.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L70,25 L40,40 L30,75 Z",
        "meepleCentroid": {
          "x": 28,
          "y": 23
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L86,52 L70,60 L66,73 L49,84 L47,100",
        "meepleCentroid": {
          "x": 65,
          "y": 72
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M69,76 L100,55 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 84
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M24,85 L35,49 L100,0 L100,46 L75,50 L44,83 L41,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 56
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_Q",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_03.jpg",
    "count": 1,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 52,
          "y": 37
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M29,76 L50,70 L70,75 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 82
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_R",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_02.jpg",
    "count": 3,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 39
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,60 L50,50 L100,60 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 83
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "base1_S",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_04.jpg",
    "count": 2,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 51,
          "y": 38
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M53,70 L47,85 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 86
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M23,83 L41,77 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 87
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,79 L74,80 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 87
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "base1_T",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_05.jpg",
    "count": 1,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 36
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M53,71 L44,84 L50,100",
        "meepleCentroid": {
          "x": 49,
          "y": 85
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M25,82 L36,78 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 26,
          "y": 86
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M55,79 L71,77 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 72,
          "y": 87
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "base1_U",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_22.jpg",
    "count": 8,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,47 L41,50 L58,36 L100,49",
        "meepleCentroid": {
          "x": 51,
          "y": 41
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M54,0 L100,0 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 19
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 79
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field1",
        "road0"
      ]
    ]
  },
  {
    "id": "base1_V",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_21.jpg",
    "count": 9,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L50,75 L47,54 L36,42 L0,46",
        "meepleCentroid": {
          "x": 46,
          "y": 52
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L58,100 L53,41 L0,37 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 32
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L38,55 L43,100 L0,100 Z",
        "meepleCentroid": {
          "x": 23,
          "y": 74
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field1",
        "road0"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "base1_W",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_23.jpg",
    "count": 4,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M70,41 L83,45 L100,49",
        "meepleCentroid": {
          "x": 81,
          "y": 43
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M52,54 L42,77 L46,100",
        "meepleCentroid": {
          "x": 44,
          "y": 75
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M0,48 L15,45 L27,45",
        "meepleCentroid": {
          "x": 21,
          "y": 42
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,43 L72,33 L55,26 L40,27 L26,37 L0,37 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M58,57 L100,52 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 75
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,54 L37,54 L37,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 74
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "field0",
        "road_w"
      ],
      [
        "field0",
        "road_e"
      ],
      [
        "field1",
        "road_e"
      ],
      [
        "field1",
        "road_s"
      ],
      [
        "field2",
        "road_w"
      ],
      [
        "road_s",
        "field2"
      ]
    ]
  },
  {
    "id": "base1_X",
    "imageUrl": "/images/BaseGame_C1/Base_Game_C1_Tile_24.jpg",
    "count": 1,
    "expansionId": "base-c1",
    "version": "C1",
    "segments": [
      {
        "id": "road_n",
        "type": "ROAD",
        "svgPath": "M46,0 L54,0 L54,46 L46,46 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 20
        }
      },
      {
        "id": "road_e",
        "type": "ROAD",
        "svgPath": "M54,46 L100,46 L100,54 L54,54 Z",
        "meepleCentroid": {
          "x": 76,
          "y": 49
        }
      },
      {
        "id": "road_s",
        "type": "ROAD",
        "svgPath": "M46,54 L54,54 L54,100 L46,100 Z",
        "meepleCentroid": {
          "x": 45,
          "y": 76
        }
      },
      {
        "id": "road_w",
        "type": "ROAD",
        "svgPath": "M0,46 L46,46 L46,54 L0,54 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 42
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M54,0 L100,0 L100,46 L54,46 Z",
        "meepleCentroid": {
          "x": 78,
          "y": 21
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M54,54 L100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 75
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,54 L46,54 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 75
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L46,46 L0,46 Z",
        "meepleCentroid": {
          "x": 21,
          "y": 20
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road_e",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road_w",
      "NORTH_CENTER": "road_n",
      "SOUTH_CENTER": "road_s"
    },
    "adjacencies": [
      [
        "field0",
        "road_e"
      ],
      [
        "field1",
        "road_e"
      ],
      [
        "field1",
        "road_s"
      ],
      [
        "field2",
        "road_s"
      ],
      [
        "field2",
        "road_w"
      ],
      [
        "field3",
        "road_w"
      ],
      [
        "field3",
        "road_n"
      ],
      [
        "field0",
        "road_n"
      ]
    ]
  }
]
