import type { TileDefinition } from '../types/tile.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: dragon-fairy-c31
 */
export const DF_TILES: TileDefinition[] = [
  {
    "id": "df31_1",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_1.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 55
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field0"
    },
    "isDragonHoard": true
  },
  {
    "id": "df31_2",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_2.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M51,0 L49,13 L33,23 L38,35 L19,46 L26,64 L51,76 L50,100",
        "meepleCentroid": {
          "x": 25,
          "y": 61
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L44,0 L42,10 L25,23 L29,31 L13,47 L20,66 L43,79 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 16,
          "y": 79
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M57,0 L100,0 L100,100 L56,100 L56,74 L92,60 L88,48 L80,41 L74,19 L56,20 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field1",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_A_left",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_A.jpg",
    "count": 0,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,100 L50,77 L64,62 L94,64 L92,48",
        "meepleCentroid": {
          "x": 64,
          "y": 64
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M57,100 L100,100 L100,71 L68,71 L57,81",
        "meepleCentroid": {
          "x": 83,
          "y": 79
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,100 L25,63 L60,46 L66,28 L100,0 L100,14 L81,38 L36,76 L39,100 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 54
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L65,27 L59,45 L25,63 L0,100 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 30
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "river0"
    },
    "startingTile": false,
    "adjacencies": [
      [
        "field1",
        "city0"
      ],
      [
        "field1",
        "river0"
      ],
      [
        "field0",
        "river0"
      ]
    ],
    "imageConfig": {
      "offsetX": 0,
      "offsetY": 0,
      "widthFactor": 2,
      "heightFactor": 1
    }
  },
  {
    "id": "df31_A_right",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_A.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,69 L23,68 L58,92 L91,84 L85,66 L68,55 L70,23 L61,12 L60,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 36
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L41,0 L42,23 L43,34 L28,17 L0,13 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 22
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M34,56 L45,48 L59,32 L66,54 L85,67 L91,85 L58,92 L32,75 Z",
        "meepleCentroid": {
          "x": 61,
          "y": 72
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,0 L53,20 L51,40 L23,50 L7,31",
        "meepleCentroid": {
          "x": 38,
          "y": 37
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "field0"
    },
    "startingTile": true,
    "adjacencies": [
      [
        "river0",
        "field1"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "field0",
        "cloister0"
      ]
    ],
    "linkedTiles": [
      {
        "dx": -1,
        "dy": 0,
        "definitionId": "df31_A_left"
      }
    ],
    "imageConfig": {
      "offsetX": 0.5,
      "offsetY": 0,
      "widthFactor": 2,
      "heightFactor": 1
    }
  },
  {
    "id": "df31_B_back_bottom",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_B_Back.jpg",
    "count": 0,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L43,0 L43,12 L18,13 L13,79 L51,90 L92,74 L91,26 L74,19 L80,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 72,
          "y": 82
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M60,0 L59,17 L50,42 L30,66",
        "meepleCentroid": {
          "x": 50,
          "y": 23
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "field0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "river0",
        "field0"
      ]
    ],
    "linkedTiles": [
      {
        "dx": 0,
        "dy": -1,
        "definitionId": "df31_B_back_top"
      }
    ],
    "flipSideDefinitionId": "df31_B_front_bottom",
    "imageConfig": {
      "offsetX": 0,
      "offsetY": 0.5,
      "widthFactor": 1,
      "heightFactor": 2
    }
  },
  {
    "id": "df31_B_back_top",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_B_Back.jpg",
    "count": 0,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,40 L62,31 L44,46 L19,57 L20,86 L44,90 L49,100 L0,100 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 45
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M100,50 L62,44 L41,59 L30,77 L51,87 L62,100",
        "meepleCentroid": {
          "x": 33,
          "y": 72
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M74,87 L49,76 L45,66 L66,54 L82,61 L100,59 L100,100 L76,100 Z",
        "meepleCentroid": {
          "x": 82,
          "y": 80
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M34,12 L59,24 L31,38 L6,26 Z",
        "meepleCentroid": {
          "x": 32,
          "y": 24
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "field0",
        "river0"
      ],
      [
        "field1",
        "river0"
      ],
      [
        "garden0",
        "field0"
      ]
    ],
    "flipSideDefinitionId": "df31_B_front_top",
    "imageConfig": {
      "offsetX": 0,
      "offsetY": 0,
      "widthFactor": 1,
      "heightFactor": 2
    }
  },
  {
    "id": "df31_B_front_bottom",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_B_Front.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L20,0 L23,20 L8,28 L9,76 L59,93 L89,76 L85,18 L72,12 L55,10 L52,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 77
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M40,0 L41,19 L51,38 L68,61",
        "meepleCentroid": {
          "x": 51,
          "y": 31
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "field0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "river0",
        "field0"
      ]
    ],
    "linkedTiles": [
      {
        "dx": 0,
        "dy": -1,
        "definitionId": "df31_B_front_top"
      }
    ],
    "flipSideDefinitionId": "df31_B_back_bottom",
    "imageConfig": {
      "offsetX": 0,
      "offsetY": 0.5,
      "widthFactor": 1,
      "heightFactor": 2
    }
  },
  {
    "id": "df31_B_front_top",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_B_Front.jpg",
    "count": 0,
    "expansionId": "dragon-fairy-c31",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L53,100 L55,91 L80,88 L81,57 L58,48 L36,31 L0,42 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 21
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M0,50 L40,44 L57,58 L69,74 L56,84 L42,90 L39,100",
        "meepleCentroid": {
          "x": 25,
          "y": 50
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,60 L19,60 L32,52 L54,67 L51,78 L26,87 L23,100 L0,100 Z",
        "meepleCentroid": {
          "x": 22,
          "y": 78
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M43,24 L65,12 L93,25 L69,38 Z",
        "meepleCentroid": {
          "x": 68,
          "y": 24
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "garden0",
        "field0"
      ]
    ],
    "flipSideDefinitionId": "df31_B_back_top",
    "imageConfig": {
      "offsetX": 0,
      "offsetY": 0,
      "widthFactor": 1,
      "heightFactor": 2
    }
  },
  {
    "id": "df31_C",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_C.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M24,74 L50,63 L72,45 L81,43 L82,31 L100,0 L100,44 L75,49 L63,66 L45,76 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 31,
          "y": 76
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,83 L73,76 L78,63 L88,56 L100,56 L100,100 L55,100 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 84
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L50,79 L67,73 L72,60 L85,50 L100,50",
        "meepleCentroid": {
          "x": 69,
          "y": 71
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L81,31 L80,42 L72,45 L48,63 L23,73 L0,100 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 34
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_D",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_D.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M31,75 L52,70 L71,74 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 83
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L71,72 L51,70 L32,74 L15,88 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 36
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "df31_E",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_E.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L87,11 L91,27 L91,66 L100,89 L100,100 L65,72 L50,70 L31,74 Z",
        "meepleCentroid": {
          "x": 43,
          "y": 32
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M92,65 L93,32 L87,11 L100,0 L100,100 Z",
        "meepleCentroid": {
          "x": 94,
          "y": 41
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M31,75 L50,70 L65,72 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 80
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_F",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_F.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L21,51 L30,61 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 32,
          "y": 18
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M84,38 L100,11 L100,89 Z",
        "meepleCentroid": {
          "x": 91,
          "y": 45
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M72,39 L100,0 L100,11 L84,38 L100,88 L100,100 L0,100 L69,51 Z",
        "meepleCentroid": {
          "x": 71,
          "y": 81
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M30,61 L21,51 L100,0 L71,40 L69,51 L0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 48
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "field1",
        "city0"
      ],
      [
        "field1",
        "city1"
      ],
      [
        "field0",
        "city1"
      ]
    ]
  },
  {
    "id": "df31_G",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_G.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L50,91 L56,83 L51,74 L49,64 L34,57 L25,47 L0,50",
        "meepleCentroid": {
          "x": 43,
          "y": 60
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L54,100 L63,79 L55,72 L54,60 L37,52 L26,43 L0,45 Z",
        "meepleCentroid": {
          "x": 48,
          "y": 30
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,54 L22,53 L33,62 L44,69 L50,83 L44,90 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_H",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_H.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,42 L74,40 L58,26 L42,25 L25,45 L0,42 Z",
        "meepleCentroid": {
          "x": 36,
          "y": 22
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M84,54 L100,55 L100,100 L57,100 L52,80 L63,75 L81,81 L92,71 Z",
        "meepleCentroid": {
          "x": 76,
          "y": 77
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,58 L35,65 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 77
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M74,48 L89,50 L100,50",
        "meepleCentroid": {
          "x": 81,
          "y": 49
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M51,100 L50,89 L46,78 L54,69",
        "meepleCentroid": {
          "x": 48,
          "y": 78
        }
      },
      {
        "id": "road2",
        "type": "ROAD",
        "svgPath": "M0,50 L15,51 L29,55",
        "meepleCentroid": {
          "x": 18,
          "y": 54
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road2",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road1"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field0",
        "road2"
      ],
      [
        "field2",
        "road2"
      ],
      [
        "field2",
        "road1"
      ],
      [
        "field1",
        "road1"
      ],
      [
        "field1",
        "road0"
      ]
    ]
  },
  {
    "id": "df31_I",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_I.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L28,22 L33,27 L52,21 L71,25 L87,16 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 71
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L86,17 L70,25 L53,21 L33,27 L29,22 L15,14 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 16
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M32,35 L60,47 L39,59 L9,45 Z",
        "meepleCentroid": {
          "x": 37,
          "y": 47
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "garden0"
      ]
    ]
  },
  {
    "id": "df31_J",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_J.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M22,66 L81,34 L88,30 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 71,
          "y": 68
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L87,29 L81,34 L74,37 L29,61 L22,66 L0,100 Z",
        "meepleCentroid": {
          "x": 33,
          "y": 29
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "df31_K",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_K.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L76,37 L52,35 L30,27 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 18
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L29,49 L41,55 L43,68 L53,73 L52,87 L50,100",
        "meepleCentroid": {
          "x": 41,
          "y": 63
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L30,27 L52,35 L76,37 L100,0 L100,100 L57,100 L60,72 L49,62 L45,51 L29,44 L0,45 Z",
        "meepleCentroid": {
          "x": 73,
          "y": 60
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M36,68 L35,58 L23,53 L0,56 L0,100 L44,100 L46,77 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 73
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_L",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_L.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L78,16 L68,28 L35,31 L16,22 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 18
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,51 L85,49 L75,49 L67,57 L55,60 L52,74 L45,82 L50,100",
        "meepleCentroid": {
          "x": 55,
          "y": 65
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L16,24 L36,32 L70,27 L100,0 L100,46 L76,41 L49,55 L36,81 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 34,
          "y": 48
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M52,83 L58,65 L71,62 L80,54 L100,56 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 77
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_M",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_M.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L0,100 L26,82 L53,79 L80,83 L100,100 L100,0 L70,25 L50,30 L30,25 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 49,
          "y": 54
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 16
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M25,84 L52,81 L77,84 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 87
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_N",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_N.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L83,85 L85,50 L61,35 L40,36 L21,61 L0,100 Z",
        "meepleCentroid": {
          "x": 54,
          "y": 18
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M16,82 L77,81 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 38,
          "y": 89
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M28,78 L29,52 L38,27 L47,47 L67,44 L75,54 L74,66 L73,77 L47,87 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 64
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "cloister0",
        "field0"
      ]
    ]
  },
  {
    "id": "df31_O",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_O.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,44 L77,46 L70,35 L53,36 L42,18 L27,45 L0,44 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 23
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,49 L85,51 L75,57",
        "meepleCentroid": {
          "x": 86,
          "y": 53
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M33,50 L44,21 L51,41 L71,40 L82,51 L77,70 L50,78 L30,70 Z",
        "meepleCentroid": {
          "x": 54,
          "y": 63
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,100 L50,89 L66,80 L61,74",
        "meepleCentroid": {
          "x": 59,
          "y": 86
        }
      },
      {
        "id": "road2",
        "type": "ROAD",
        "svgPath": "M0,50 L17,50 L19,77 L36,76",
        "meepleCentroid": {
          "x": 15,
          "y": 52
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M57,91 L72,83 L72,76 L80,62 L91,57 L100,55 L100,100 L55,100 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 78
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,57 L10,57 L12,80 L32,83 L46,81 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 89
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road2",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road1"
    },
    "hasDragon": true,
    "adjacencies": [
      [
        "cloister0",
        "field0"
      ],
      [
        "cloister0",
        "road0"
      ],
      [
        "cloister0",
        "road1"
      ],
      [
        "cloister0",
        "road2"
      ],
      [
        "cloister0",
        "field1"
      ],
      [
        "cloister0",
        "field2"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "field1",
        "road1"
      ],
      [
        "field2",
        "road1"
      ],
      [
        "field2",
        "road2"
      ],
      [
        "field0",
        "road2"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "df31_P",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_P.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L100,100 L70,72 L50,67 L27,75 L0,100 L0,0 L22,18 L53,22 L75,18 Z",
        "meepleCentroid": {
          "x": 53,
          "y": 46
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,0 L50,11 M52,89 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 9
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L46,14 L55,14 L56,0 L100,0 L75,18 L51,20 L22,16 Z",
        "meepleCentroid": {
          "x": 34,
          "y": 13
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M58,84 L49,83 L45,100 L0,100 L27,75 L53,69 L71,74 L93,93 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 44,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "df31_Q",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_Q.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,51 L12,51 L20,54",
        "meepleCentroid": {
          "x": 16,
          "y": 54
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M77,46 L89,49 L100,50",
        "meepleCentroid": {
          "x": 86,
          "y": 50
        }
      },
      {
        "id": "road2",
        "type": "ROAD",
        "svgPath": "M47,74 L47,86 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 88
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,45 L58,31 L38,33 L17,45 L0,45 Z",
        "meepleCentroid": {
          "x": 48,
          "y": 21
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,81 L84,56 L100,56 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 75
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M23,80 L46,100 L0,100 L0,54 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road1",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road2"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "field1",
        "road1"
      ],
      [
        "field1",
        "road2"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road2",
        "field2"
      ],
      [
        "field0",
        "road1"
      ]
    ]
  },
  {
    "id": "df31_R",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_R.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L74,74 L51,68 L30,73 L0,100 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 36
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,74 L51,68 L73,74 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 40,
          "y": 84
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "df31_S",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_S.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L23,47 L35,58 L49,62 L50,76 L56,83 L49,90 L49,100",
        "meepleCentroid": {
          "x": 43,
          "y": 59
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L35,26 L50,21 L67,25 L85,21 L100,0 L100,100 L57,100 L62,83 L56,75 L55,60 L38,54 L24,43 L0,47 Z",
        "meepleCentroid": {
          "x": 55,
          "y": 42
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,56 L21,54 L31,62 L42,66 L44,78 L49,85 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 75
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L81,19 L67,24 L50,20 L35,24 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 16
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_T",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_T.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L31,35 L72,28 L100,0 L100,44 L75,43 L49,60 L38,83 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 72
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L45,83 L51,73 L50,64 L67,56 L78,48 L100,50",
        "meepleCentroid": {
          "x": 75,
          "y": 50
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M51,84 L58,67 L71,61 L79,54 L100,55 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 78
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L75,16 L67,27 L48,30 L32,31 L19,21 L13,12 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 21
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_U",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_U.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L84,21 L80,35 L65,49 L24,71 Z",
        "meepleCentroid": {
          "x": 33,
          "y": 30
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L82,50 L72,60 L67,72 L50,75 L44,84 L50,92 L50,100",
        "meepleCentroid": {
          "x": 68,
          "y": 69
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M84,21 L100,0 L100,46 L74,50 L64,65 L43,74 L38,84 L44,94 L44,100 L0,100 L24,71 L65,49 L80,36 Z",
        "meepleCentroid": {
          "x": 88,
          "y": 33
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M84,57 L72,74 L53,81 L55,100 L100,100 L100,55 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 81
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "df31_V",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_V.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,56 L16,53 L21,42 L36,31 L55,25 L56,0 L100,0 L100,44 L79,47 L70,66 L57,71 L45,81 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 46,
          "y": 51
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L45,0 L44,18 L32,19 L24,28 L14,33 L8,44 L0,44 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 17
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M56,85 L66,79 L78,75 L86,57 L100,55 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 86,
          "y": 81
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L12,50 L18,37 L31,32 L35,23 L50,21 L50,0",
        "meepleCentroid": {
          "x": 29,
          "y": 29
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,100 L51,81 L62,73 L74,71 L77,58 L86,50 L100,50",
        "meepleCentroid": {
          "x": 74,
          "y": 69
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field2",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "road1",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road1"
    },
    "hasMagicPortal": true,
    "adjacencies": [
      [
        "field1",
        "road0"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "field0",
        "road1"
      ],
      [
        "field2",
        "road1"
      ]
    ]
  },
  {
    "id": "df31_W",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_W.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,56 L20,56 L21,79 L42,80 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 83
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L56,100 L57,68 L34,67 L31,45 L0,45 Z",
        "meepleCentroid": {
          "x": 78,
          "y": 60
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L26,51 L27,76 L50,73 L50,100",
        "meepleCentroid": {
          "x": 30,
          "y": 74
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "df31_X",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_X.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,25 L50,30 L30,25 Z",
        "meepleCentroid": {
          "x": 53,
          "y": 11
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,100 L21,84 L28,59 L26,24 L53,32 L72,25 L100,0 L100,100 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 68
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,0 L27,32 L26,60 L19,85 L13,86 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 54
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "field0",
        "city1"
      ],
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "df31_Y",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_Y.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L75,38 L48,38 L30,30 Z",
        "meepleCentroid": {
          "x": 54,
          "y": 21
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,31 L49,39 L76,39 L100,0 L100,100 L0,100 L0,0 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "df31_Z",
    "imageUrl": "/images/DragonAndFairy_C31/Dragon_And_Fairy_C31_Tile_Z.jpg",
    "count": 1,
    "expansionId": "dragon-fairy-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M55,67 L62,81 L51,89 L51,100",
        "meepleCentroid": {
          "x": 50,
          "y": 86
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L57,100 L57,93 L70,81 L58,60 L47,66 L55,79 L45,88 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 20
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "isDragonHoard": true,
    "adjacencies": [
      [
        "field0",
        "road0"
      ]
    ]
  }
]
