import type { TileDefinition } from '../types/tile.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: inns-cathedrals-c31
 */
export const IC_C31_TILES: TileDefinition[] = [
  {
    "id": "ic31_A",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_A.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,57 L45,55 L42,100 L0,100 Z",
        "meepleCentroid": {
          "x": 28,
          "y": 71
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,100 L56,100 L71,59 L37,40 L0,45 Z",
        "meepleCentroid": {
          "x": 53,
          "y": 18
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M0,50 L37,44 L67,64 L53,80 L50,100",
        "meepleCentroid": {
          "x": 59,
          "y": 55
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field1",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field1",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_B",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_B.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,42 L0,44 Z",
        "meepleCentroid": {
          "x": 34,
          "y": 28
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,58 L65,87 L100,69 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 79
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M0,50 L45,59 L65,54 L80,59 L100,49",
        "meepleCentroid": {
          "x": 53,
          "y": 55
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M42,73 L69,60 L92,72 L63,86 Z",
        "meepleCentroid": {
          "x": 67,
          "y": 71
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "garden0",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_C",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_C.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,43 L54,14 L0,42 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 28
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,86 L100,58 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 76
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,57 L42,81 L43,100 L0,100 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 75
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M83,52 L92,50 L100,50",
        "meepleCentroid": {
          "x": 80,
          "y": 52
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,100 L49,84 L51,74 L55,66",
        "meepleCentroid": {
          "x": 51,
          "y": 80
        }
      },
      {
        "id": "road2",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M0,50 L11,50 L23,42 L39,44",
        "meepleCentroid": {
          "x": 27,
          "y": 43
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road2",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field0",
        "road2"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "road2",
        "field2"
      ],
      [
        "field1",
        "road0"
      ]
    ]
  },
  {
    "id": "ic31_D",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_D.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,46 L73,38 L51,36 L43,21 L32,47 L0,43 Z",
        "meepleCentroid": {
          "x": 55,
          "y": 23
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,57 L10,58 L14,83 L80,74 L77,61 L100,56 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 84
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M76,55 L91,51 L100,50",
        "meepleCentroid": {
          "x": 84,
          "y": 52
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M0,50 L18,54 L20,77 L37,77",
        "meepleCentroid": {
          "x": 16,
          "y": 52
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M41,21 L53,40 L71,43 L77,68 L58,78 L30,70 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 52
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road1",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "cloister0",
        "field0"
      ],
      [
        "cloister0",
        "road0"
      ],
      [
        "cloister0",
        "field1"
      ],
      [
        "cloister0",
        "road1"
      ],
      [
        "field0",
        "road1"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "field1",
        "road1"
      ]
    ]
  },
  {
    "id": "ic31_E",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_E.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L28,23 L0,45 Z",
        "meepleCentroid": {
          "x": 21,
          "y": 20
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M75,75 L100,55 L100,100 L55,100 Z",
        "meepleCentroid": {
          "x": 85,
          "y": 85
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,58 L57,19 L57,0 L100,0 L100,41 L77,51 L44,85 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 56,
          "y": 49
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L13,49 L18,39 L28,33 L36,23 L50,22 L52,0",
        "meepleCentroid": {
          "x": 30,
          "y": 29
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M49,100 L50,84 L60,74 L74,69 L82,52 L100,50",
        "meepleCentroid": {
          "x": 73,
          "y": 70
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field2",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road1",
      "NORTH_RIGHT": "field2",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road1",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_F",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_F.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M84,32 L100,0 L100,43 L51,55 Z",
        "meepleCentroid": {
          "x": 87,
          "y": 36
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M26,70 L100,62 L100,100 L17,100 Z",
        "meepleCentroid": {
          "x": 54,
          "y": 81
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M39,59 L60,65 L82,54 L100,50",
        "meepleCentroid": {
          "x": 69,
          "y": 59
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L86,16 L85,26 L59,49 L20,69 L23,87 L0,100 L0,0 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 29
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_G",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_G.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L0,100 L23,71 L64,51 L80,39 L88,16 L100,0 L94,0 L78,16 L19,21 Z",
        "meepleCentroid": {
          "x": 26,
          "y": 45
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L94,0 L76,16 L18,17 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 13
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M22,74 L81,42 L89,17 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 73
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field1",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_H",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_H.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L82,19 L68,25 L52,23 L35,26 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 12
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,0 L100,100 L88,83 L80,60 L84,26 Z",
        "meepleCentroid": {
          "x": 89,
          "y": 49
        }
      },
      {
        "id": "city2",
        "type": "CITY",
        "svgPath": "M0,100 L100,100 L75,76 L58,70 L36,75 L20,88 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 85
        }
      },
      {
        "id": "city3",
        "type": "CITY",
        "svgPath": "M0,0 L18,16 L28,37 L27,60 L20,78 L14,85 L0,100 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 47
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M27,25 L78,25 L77,53 L52,38 L30,52 L58,66 L78,53 L80,68 L34,71 L21,85 L30,51 Z",
        "meepleCentroid": {
          "x": 42,
          "y": 37
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M29,51 L53,38 L79,53 L58,66 Z",
        "meepleCentroid": {
          "x": 56,
          "y": 52
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city3",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city2",
      "WEST_RIGHT": "city3",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city2",
      "WEST_CENTER": "city3",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city2"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city3"
      ],
      [
        "field0",
        "city2"
      ],
      [
        "field0",
        "city1"
      ],
      [
        "garden0",
        "field0"
      ]
    ]
  },
  {
    "id": "ic31_I",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_I.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M83,21 L100,0 L100,45 L77,43 L54,35 L54,31 Z",
        "meepleCentroid": {
          "x": 87,
          "y": 28
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M76,55 L100,56 L100,100 L83,82 L60,74 L60,69 Z",
        "meepleCentroid": {
          "x": 82,
          "y": 77
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,55 L37,61 L48,69 L47,74 L34,73 L15,78 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 70
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L24,25 L43,32 L33,42 L31,50 L0,46 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 32
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M76,48 L89,49 L100,51",
        "meepleCentroid": {
          "x": 85,
          "y": 47
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M0,50 L34,56",
        "meepleCentroid": {
          "x": 20,
          "y": 53
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L79,21 L60,26 L37,28 L19,20 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 15
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,100 L16,79 L34,75 L63,76 L79,81 L100,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "road1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "field3",
        "road1"
      ],
      [
        "city1",
        "field2"
      ],
      [
        "city1",
        "field1"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "field0",
        "city0"
      ],
      [
        "field3",
        "city0"
      ]
    ]
  },
  {
    "id": "ic31_J",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_J.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M51,42 L100,5 L100,100 L55,100 L62,65 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 55
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L16,23 L43,29 L34,47 L49,63 L39,80 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 57
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M57,24 L42,43 L56,62 L53,69 L46,79 L51,100",
        "meepleCentroid": {
          "x": 56,
          "y": 62
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L79,19 L66,24 L33,26 L15,21 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 19
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "city0"
      ],
      [
        "field0",
        "city0"
      ],
      [
        "field1",
        "city0"
      ]
    ]
  },
  {
    "id": "ic31_Ka",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_Ka.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "hasCathedral": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city0"
    }
  },
  {
    "id": "ic31_Kb",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_Kb.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L0,100 Z",
        "hasCathedral": true,
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city0"
    }
  },
  {
    "id": "ic31_L",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_L.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M38,73 L37,63 L88,32 L100,0 L100,42 L77,43 L49,59 L37,82 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 26,
          "y": 80
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M76,56 L100,57 L100,100 L55,100 L57,70 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 75
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M100,50 L78,48 L67,57 L53,61 L52,72 L44,80 L49,89 L50,100",
        "meepleCentroid": {
          "x": 60,
          "y": 59
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L86,30 L72,41 L35,62 L37,72 L18,80 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 32,
          "y": 32
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "ic31_M",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_M.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L31,29 L50,39 L79,38 L100,0 L100,100 L57,100 L60,71 L47,63 L41,45 L0,45 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 55
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,56 L30,56 L37,70 L47,77 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 23,
          "y": 76
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M0,50 L22,49 L37,50 L41,67 L54,74 L50,100",
        "meepleCentroid": {
          "x": 40,
          "y": 63
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L78,37 L50,39 L32,29 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 22
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "field1",
        "road0"
      ]
    ]
  },
  {
    "id": "ic31_N",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_N.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M61,78 L59,51 L53,40 L73,31 L100,0 L100,100 L55,100 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 50
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M30,76 L45,70 L48,81 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 81
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M49,66 L56,76 L51,87 L50,100",
        "meepleCentroid": {
          "x": 55,
          "y": 78
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L69,29 L51,37 L56,62 L28,75 L0,100 Z",
        "meepleCentroid": {
          "x": 28,
          "y": 30
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "ic31_O",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_O.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M29,27 L79,25 L79,56 L88,88 L100,100 L0,100 L19,85 L29,59 Z",
        "meepleCentroid": {
          "x": 53,
          "y": 57
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L82,19 L68,24 L51,23 L33,23 Z",
        "meepleCentroid": {
          "x": 55,
          "y": 13
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,0 L100,100 L89,87 L80,60 L80,37 L87,18 Z",
        "meepleCentroid": {
          "x": 90,
          "y": 47
        }
      },
      {
        "id": "city2",
        "type": "CITY",
        "svgPath": "M0,0 L20,20 L28,38 L26,61 L17,83 L0,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city2",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city2",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city2",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "city1"
      ],
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city2"
      ]
    ]
  },
  {
    "id": "ic31_P",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_P.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M23,66 L81,37 L92,21 L100,0 L100,100 L83,86 L51,76 L23,82 L0,100 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 60
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L92,8 L89,24 L78,37 L23,65 L11,83 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 43,
          "y": 27
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,100 L100,100 L84,89 L71,84 L45,79 L25,83 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 51,
          "y": 81
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city1"
      ]
    ]
  },
  {
    "id": "ic31_Q",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_Q.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L43,15 L38,22 L38,27 L27,24 Z",
        "meepleCentroid": {
          "x": 27,
          "y": 16
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,0 L100,0 L83,14 L63,26 L54,24 L56,18 Z",
        "meepleCentroid": {
          "x": 71,
          "y": 13
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M57,85 L82,88 L100,100 L57,100 Z",
        "meepleCentroid": {
          "x": 74,
          "y": 90
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M26,87 L45,83 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 27,
          "y": 90
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M51,0 L50,14 L44,24 L50,30",
        "meepleCentroid": {
          "x": 49,
          "y": 19
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,100 L50,92 L50,83",
        "meepleCentroid": {
          "x": 50,
          "y": 86
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L26,26 L59,31 L84,16 L100,0 L100,100 L84,85 L60,80 L40,80 L21,85 L0,100 Z",
        "hasPennant": true,
        "meepleCentroid": {
          "x": 50,
          "y": 53
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field3",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "field3"
      ],
      [
        "road1",
        "field3"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road1",
        "city0"
      ]
    ]
  },
  {
    "id": "ic31_R",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_R.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M73,59 L78,76 L100,100 L56,100 L52,80 L45,65 L51,52 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 83
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L18,19 L36,25 L73,25 L73,45 L49,41 L35,51 L33,70 L45,86 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 55
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L50,84 L37,66 L43,50 L60,47 L76,51",
        "meepleCentroid": {
          "x": 43,
          "y": 76
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L65,24 L34,23 L17,17 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 17
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,0 L79,26 L75,51 L81,73 L100,100 Z",
        "meepleCentroid": {
          "x": 91,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field0",
        "city1"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "city1",
        "field1"
      ],
      [
        "road0",
        "city1"
      ]
    ]
  },
  {
    "id": "ic31_S",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_S.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M28,24 L70,26 L85,18 L100,0 L100,100 L54,100 L55,87 L65,74 L66,56 L54,44 L30,44 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 51
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M20,80 L28,57 L46,51 L56,57 L54,73 L47,88 L47,100 L0,100 Z",
        "meepleCentroid": {
          "x": 33,
          "y": 80
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 L51,84 L62,70 L61,53 L48,46 L26,52",
        "meepleCentroid": {
          "x": 57,
          "y": 77
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L82,17 L67,25 L50,22 L31,22 Z",
        "meepleCentroid": {
          "x": 55,
          "y": 10
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,0 L19,20 L26,38 L26,64 L15,83 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 51
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city1"
      ],
      [
        "field1",
        "city1"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "ic31_T",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_T.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M57,0 L100,0 L100,40 L87,41 L83,54 L71,58 L64,43 L49,27 Z",
        "meepleCentroid": {
          "x": 76,
          "y": 27
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M78,77 L100,62 L100,100 L55,100 L56,87 L40,82 L34,74 L41,69 L48,76 L64,80 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 81
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,62 L22,56 L27,64 L20,76 L30,90 L44,94 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 78
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L44,0 L34,28 L50,48 L40,49 L29,39 L0,40 Z",
        "meepleCentroid": {
          "x": 21,
          "y": 21
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M52,0 L47,16 L39,28 L53,40 L63,52 L38,59 L28,75 L35,85 L50,90 L50,100",
        "meepleCentroid": {
          "x": 33,
          "y": 68
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M100,50 L82,64 L66,70 L50,64 L25,47 L0,50",
        "meepleCentroid": {
          "x": 63,
          "y": 68
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "river0"
      ],
      [
        "road0",
        "field3"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ],
      [
        "river0",
        "field2"
      ],
      [
        "river0",
        "field3"
      ],
      [
        "river0",
        "field0"
      ]
    ]
  },
  {
    "id": "ic31_U",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_U.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M86,20 L100,0 L100,45 L72,45 L58,39 L57,31 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 35
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,56 L43,63 L49,68 L49,74 L32,74 L13,78 L0,100 Z",
        "meepleCentroid": {
          "x": 21,
          "y": 67
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,0 L21,24 L43,30 L46,46 L61,53 L100,55 L100,100 L89,85 L72,76 L62,75 L58,60 L47,52 L0,44 Z",
        "meepleCentroid": {
          "x": 28,
          "y": 39
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M49,28 L52,43 L67,50 L100,50",
        "meepleCentroid": {
          "x": 66,
          "y": 49
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M0,50 L29,55 L50,58 L55,75",
        "meepleCentroid": {
          "x": 32,
          "y": 56
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L85,12 L85,18 L61,26 L39,27 L21,22 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 13
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,100 L100,100 L85,89 L69,77 L32,75 L14,80 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 88
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field2",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "field2",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "road1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "road1",
        "city1"
      ],
      [
        "field2",
        "city1"
      ]
    ]
  },
  {
    "id": "ic31_V",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_V.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M78,20 L100,0 L100,45 L90,44 L90,29 Z",
        "meepleCentroid": {
          "x": 89,
          "y": 22
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M65,30 L77,35 L79,54 L100,55 L100,100 L56,100 L56,91 L50,73 L53,53 L62,51 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 79
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,56 L16,56 L27,50 L38,52 L38,73 L45,92 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 76
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L18,19 L19,39 L12,45 L0,46 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 27
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M69,24 L84,32 L84,49 L100,50",
        "meepleCentroid": {
          "x": 88,
          "y": 50
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,100 L50,92 L43,72 L47,50",
        "meepleCentroid": {
          "x": 45,
          "y": 75
        }
      },
      {
        "id": "road2",
        "type": "ROAD",
        "svgPath": "M0,50 L15,50 L26,43",
        "meepleCentroid": {
          "x": 16,
          "y": 50
        }
      },
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L76,17 L60,28 L60,50 L31,49 L21,38 L19,19 Z",
        "meepleCentroid": {
          "x": 44,
          "y": 17
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road2",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "field0",
        "road0"
      ],
      [
        "field0",
        "city0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road1"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "road2"
      ],
      [
        "city0",
        "field3"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "field1",
        "road1"
      ],
      [
        "field2",
        "road1"
      ],
      [
        "field2",
        "road2"
      ],
      [
        "field3",
        "road2"
      ]
    ]
  },
  {
    "id": "ic31_W",
    "imageUrl": "/images/InnsAndCathedrals_C31/Inns_And_Cathedrals_C31_Tile_W.jpg",
    "count": 1,
    "expansionId": "inns-cathedrals-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M55,0 L100,0 L100,45 L90,43 L84,30 L70,23 L67,15 L57,8 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 19
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M58,91 L76,77 L80,61 L100,56 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 78
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,56 L13,56 L25,76 L41,84 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 81
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L45,0 L42,13 L32,17 L26,23 L15,28 L8,44 L0,45 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 14
        }
      },
      {
        "id": "field4",
        "type": "FIELD",
        "svgPath": "M40,26 L56,24 L63,36 L73,40 L77,48 L67,55 L64,69 L53,78 L34,68 L28,54 L20,46 L23,37 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 45
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "hasInn": true,
        "svgPath": "M14,48 L20,32 L30,29 L37,20 L48,19 L50,10 L62,19 L65,29 L78,34 L83,45 L91,50 L74,56 L70,73 L55,84 L50,92 L48,80 L31,72 L23,56 Z M0,50 L14,48 M50,0 L50,10 M100,50 L91,50 M50,100 L50,92",
        "meepleCentroid": {
          "x": 28,
          "y": 70
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field3"
      ],
      [
        "road0",
        "field4"
      ]
    ]
  }
]
