import type { TileDefinition } from '../types/tile.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: river-c3
 */
export const RIVER_C3_TILES: TileDefinition[] = [
  {
    "id": "river_c3_A",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_A.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L43,0 L36,26 L28,64 L42,75 L40,100 L0,100 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 49
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,30 Q45,60 50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 65
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M51,0 L42,23 L62,34 L76,49 L100,50",
        "meepleCentroid": {
          "x": 58,
          "y": 33
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M57,0 L100,0 L100,45 L79,44 L65,29 L48,22 Z",
        "meepleCentroid": {
          "x": 76,
          "y": 21
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M76,53 L100,54 L100,100 L58,100 L61,67 L48,64 L65,44 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 74
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field2",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "river0"
    },
    "startingTile": true,
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "river0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "field2",
        "river0"
      ],
      [
        "field2",
        "road0"
      ]
    ]
  },
  {
    "id": "river_c3_B",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_B.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L81,24 Q60,50 29,28 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 14
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,100 Q53,84 37,85 Q29,78 30,72 Q41,51 60,53 Q72,57 72,48 Q65,41 60,38",
        "meepleCentroid": {
          "x": 46,
          "y": 86
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M0,49 Q33,44 42,62 Q72,79 82,61 Q90,44 100,48",
        "meepleCentroid": {
          "x": 71,
          "y": 68
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M76,38 L100,1 L100,40 L85,42 L84,54 L78,54 L77,46 L68,40 Z",
        "meepleCentroid": {
          "x": 87,
          "y": 30
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M100,54 L100,100 L54,100 L54,85 L39,83 L36,74 L44,70 L51,77 L84,75 L85,66 Z",
        "meepleCentroid": {
          "x": 79,
          "y": 85
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,59 L14,59 L24,55 L31,62 L23,75 L31,86 L44,89 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 79
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L35,34 L53,40 L59,43 L54,47 L44,49 L29,40 L0,40 Z",
        "meepleCentroid": {
          "x": 16,
          "y": 31
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ],
      [
        "river0",
        "field2"
      ],
      [
        "field3",
        "city0"
      ],
      [
        "field3",
        "river0"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field3"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ]
    ]
  },
  {
    "id": "river_c3_C",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_C.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 Q49,60 0,0 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 15
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M0,50 L100,50",
        "meepleCentroid": {
          "x": 50,
          "y": 50
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M100,0 Q49,60 0,0 L0,40 L100,40 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 35
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,58 L100,58 L100,100 Q36,38 0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 64
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,100 Q36,38 0,100 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "field1",
        "city1"
      ]
    ]
  },
  {
    "id": "river_c3_D",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_D.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M52,0 L46,27 L39,54 L47,76 L50,99 M45,37 L63,66 L49,100",
        "meepleCentroid": {
          "x": 50,
          "y": 51
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M61,0 L100,0 L100,100 L59,100 L70,65 L53,38 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 50
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L39,0 L37,25 L29,40 L30,59 L38,71 L40,100 L0,100 Z",
        "meepleCentroid": {
          "x": 17,
          "y": 52
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field1",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "river_c3_E",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_E.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 Q54,44 18,35 Z",
        "meepleCentroid": {
          "x": 68,
          "y": 28
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,100 Q50,55 0,50",
        "meepleCentroid": {
          "x": 34,
          "y": 66
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M62,72 L80,77 L100,100 L58,100 L54,70 L22,42 L0,39 L0,0 L18,34 L61,61 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 57
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,60 L16,59 L18,71 L28,72 L34,77 L29,84 L38,88 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 80
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "river_c3_F",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_F.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,0 Q50,10 35,14 Q0,38 45,36 Q88,26 73,55 Q38,64 50,70 Q56,80 50,83 L50,100",
        "meepleCentroid": {
          "x": 50,
          "y": 34
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L40,0 L11,22 L13,39 L38,48 L64,41 L68,48 L38,61 L39,72 L45,78 L41,86 L41,100 L0,100 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 70
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M59,86 L63,77 L58,69 L77,64 L86,43 L69,24 L33,30 L32,23 L57,11 L61,0 L100,0 L100,100 L60,100 Z",
        "meepleCentroid": {
          "x": 81,
          "y": 77
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field1",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "river_c3_G",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_G.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M45,0 Q87,60 0,51",
        "meepleCentroid": {
          "x": 51,
          "y": 45
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L40,0 L40,12 L49,17 L51,32 L29,47 L19,40 L0,41 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 20
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,100 L0,60 L15,60 L42,67 L77,32 L67,24 L74,15 L58,6 L60,0 L100,0 L100,100 Z",
        "meepleCentroid": {
          "x": 72,
          "y": 71
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field1",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "river_c3_H",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_H.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M25,15 L48,15 L48,40 L25,40 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 43
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M100,50 L0,50",
        "meepleCentroid": {
          "x": 48,
          "y": 87
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M0,50 Q36,64 63,76 Q78,76 87,53 Q92,50 100,50",
        "meepleCentroid": {
          "x": 17,
          "y": 56
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,41 L86,40 L85,47 L76,51 L0,38 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 15
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M54,89 L51,81 L73,83 L90,70 L92,60 L100,56 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 78,
          "y": 88
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M45,89 L35,84 L35,75 L19,66 L10,64 L9,59 L0,59 L0,100 L45,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 82
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "cloister0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ],
      [
        "river0",
        "field2"
      ],
      [
        "road0",
        "cloister0"
      ]
    ]
  },
  {
    "id": "river_c3_I",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_I.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L42,0 L46,13 L50,22 L36,25 L29,39 L11,45 L0,46 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 21
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M100,49 Q57,38 50,100",
        "meepleCentroid": {
          "x": 63,
          "y": 61
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L30,45 L41,29 L56,26 L52,13 L49,0",
        "meepleCentroid": {
          "x": 38,
          "y": 37
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,55 L35,48 L44,35 L64,22 L53,0 L100,0 L100,39 L65,37 L42,57 L45,78 L49,84 L40,89 L40,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 72
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M83,56 L100,60 L100,100 L59,100 L62,91 L75,89 L75,78 L85,80 L73,62 Z",
        "meepleCentroid": {
          "x": 83,
          "y": 78
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field2",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "field1",
        "road0"
      ],
      [
        "field1",
        "river0"
      ],
      [
        "field2",
        "river0"
      ]
    ]
  },
  {
    "id": "river_c3_J",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_J.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,100 Q51,49 100,49",
        "meepleCentroid": {
          "x": 64,
          "y": 66
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L100,36 L69,39 L44,53 L36,71 L40,100 L0,100 Z",
        "meepleCentroid": {
          "x": 25,
          "y": 30
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M100,59 L87,58 L78,77 L64,84 L55,100 L100,100 Z",
        "meepleCentroid": {
          "x": 86,
          "y": 79
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "river0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "river_c3_K",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_K.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L9,49 L16,41 L31,40 L42,44 L65,61 L87,51 L100,50",
        "meepleCentroid": {
          "x": 63,
          "y": 60
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M50,0 L41,21 L49,36 L31,59 L35,74 L52,100",
        "meepleCentroid": {
          "x": 43,
          "y": 23
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L0,46 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 15
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M54,0 L100,0 L100,46 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 15
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M100,54 L100,100 L54,100 Z",
        "meepleCentroid": {
          "x": 80,
          "y": 80
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,54 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 82
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field1",
      "WEST_LEFT": "field3",
      "EAST_RIGHT": "field2",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "field1",
      "SOUTH_RIGHT": "field3",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ],
      [
        "river0",
        "field2"
      ],
      [
        "river0",
        "field3"
      ],
      [
        "road0",
        "field3"
      ]
    ]
  },
  {
    "id": "river_c3_L",
    "imageUrl": "/images/River1_C3/River_I_C3_Tile_L.png",
    "count": 1,
    "expansionId": "river-c3",
    "segments": [
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M15,55 L45,55 L45,85 L15,85 Z",
        "meepleCentroid": {
          "x": 62,
          "y": 67
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M38,33 Q58,33 60,13 Q50,13 48,0",
        "meepleCentroid": {
          "x": 58,
          "y": 17
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L39,0 L43,12 L55,19 L44,25 L18,23 L17,30 L24,32 L14,44 L28,50 L8,61 L16,70 L17,83 L35,82 L34,74 L28,69 L36,66 L34,61 L53,56 L55,43 L62,47 L82,51 L88,35 L69,31 L64,24 L68,12 L57,7 L58,0 L100,0 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 15,
          "y": 17
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "river0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "river0",
        "field0"
      ],
      [
        "field0",
        "cloister0"
      ]
    ]
  }
]
