import type { TileDefinition } from '../types/tile.ts'

/** 
 * AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
 * Generated by `npm run download-tiles` (scripts/download-tiles.ts)
 * Expansions: traders-builders-c31
 */
export const TB_C31_TILES: TileDefinition[] = [
  {
    "id": "tb31_A",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_A.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L78,22 L82,38 L69,51 L61,47 L39,52 L39,30 L27,18 L21,20 Z",
        "meepleCentroid": {
          "x": 57,
          "y": 22
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M57,78 L69,78 L78,73 L87,51 L100,50",
        "meepleCentroid": {
          "x": 80,
          "y": 69
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L39,54 L70,52 L85,38 L100,0 L100,50 L100,42 L79,49 L72,67 L49,61 L41,79 L74,85 L90,65 L100,56 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 24,
          "y": 68
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "field0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "tb31_B",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_B.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M63,0 L79,36 L67,50 L77,52 L100,43 L100,0 Z",
        "meepleCentroid": {
          "x": 82,
          "y": 29
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M45,71 L100,62 L100,100 L60,100 Z",
        "meepleCentroid": {
          "x": 74,
          "y": 78
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,56 L24,55 L38,100 L0,100 Z",
        "meepleCentroid": {
          "x": 20,
          "y": 76
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L43,0 L53,40 L0,42 Z",
        "meepleCentroid": {
          "x": 26,
          "y": 26
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M52,100 L34,69 L71,34 L50,0",
        "meepleCentroid": {
          "x": 39,
          "y": 64
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M0,50 L37,44 L70,62 L100,50",
        "meepleCentroid": {
          "x": 72,
          "y": 60
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field2",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "field3",
      "EAST_CENTER": "road1",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "road1",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "road0",
        "field3"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "road1",
        "field0"
      ],
      [
        "road1",
        "field3"
      ],
      [
        "road1",
        "field2"
      ]
    ]
  },
  {
    "id": "tb31_C",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_C.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M13,22 L0,0 L100,0 L80,19 L57,28 L31,28 Z",
        "hasPennant": false,
        "meepleCentroid": {
          "x": 46,
          "y": 17
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M42,69 L93,70 L95,48 L65,43 L67,25 L82,19 L100,0 L100,100 L57,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 76
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,57 L32,53 L26,68 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 18,
          "y": 74
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,0 L13,23 L33,29 L47,29 L45,39 L0,42 Z",
        "meepleCentroid": {
          "x": 19,
          "y": 35
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M0,50 L36,44 L63,61 L71,61",
        "meepleCentroid": {
          "x": 17,
          "y": 48
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M53,23 L61,36 L32,69 L50,100",
        "meepleCentroid": {
          "x": 34,
          "y": 69
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field2",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "road0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "road1"
      ],
      [
        "road1",
        "field0"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "field0",
        "road0"
      ]
    ]
  },
  {
    "id": "tb31_D",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_D.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L100,100 L66,83 L38,33 L33,20 Z",
        "commodity": "WHEAT",
        "meepleCentroid": {
          "x": 78,
          "y": 28
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L20,27 L23,40 L16,84 Z",
        "meepleCentroid": {
          "x": 8,
          "y": 46
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M51,62 L65,84 L100,100 L58,100 Z",
        "meepleCentroid": {
          "x": 68,
          "y": 88
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M16,83 L24,38 L20,25 L0,0 L33,20 L45,47 L36,62 L44,79 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 31,
          "y": 63
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M49,51 L44,62 L50,78 L51,100",
        "meepleCentroid": {
          "x": 49,
          "y": 75
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city1",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city1",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "city1",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_E",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_E.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L23,17 L41,16 L62,21 L100,0 L100,100 L71,72 L40,69 L0,100 Z",
        "commodity": "WHEAT",
        "meepleCentroid": {
          "x": 51,
          "y": 44
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M52,68 L48,79 L53,89 L49,100",
        "meepleCentroid": {
          "x": 50,
          "y": 82
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M59,71 L71,72 L100,100 L57,100 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 86
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M24,82 L43,69 L41,80 L47,89 L41,100 L0,100 Z",
        "meepleCentroid": {
          "x": 34,
          "y": 86
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L68,16 L24,16 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 13
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field2",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field2",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field2",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field2",
        "city0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_F",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_F.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L57,47 L57,57 L0,100 Z",
        "commodity": "WHEAT",
        "meepleCentroid": {
          "x": 38,
          "y": 28
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M57,47 L100,0 L100,100 L57,100 L67,83 L71,69 L58,60 Z",
        "meepleCentroid": {
          "x": 82,
          "y": 57
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M44,68 L61,75 L42,100 L0,100 Z",
        "meepleCentroid": {
          "x": 37,
          "y": 84
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M46,60 L68,71 L65,82 L50,100",
        "meepleCentroid": {
          "x": 67,
          "y": 80
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_G",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_G.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L90,18 L82,33 L57,49 L28,65 Z",
        "commodity": "WHEAT",
        "hasPennant": false,
        "meepleCentroid": {
          "x": 50,
          "y": 15
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,100 L28,66 L83,34 L100,0 L100,100 Z",
        "meepleCentroid": {
          "x": 63,
          "y": 77
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ]
    ]
  },
  {
    "id": "tb31_H",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_H.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L100,100 L70,75 L50,70 L30,75 Z",
        "commodity": "WHEAT",
        "meepleCentroid": {
          "x": 50,
          "y": 34
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,75 L50,70 L70,75 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ]
    ]
  },
  {
    "id": "tb31_I",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_I.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L90,9 L88,60 L100,100 L72,73 L33,70 L0,100 Z",
        "commodity": "WHEAT",
        "meepleCentroid": {
          "x": 42,
          "y": 34
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M100,0 L91,10 L88,35 L90,64 L100,100 Z",
        "meepleCentroid": {
          "x": 91,
          "y": 44
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M53,71 L72,75 L100,100 L58,100 Z",
        "meepleCentroid": {
          "x": 66,
          "y": 86
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M33,71 L44,70 L43,100 L0,100 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 87
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M49,69 L50,76 L49,86 L50,100",
        "meepleCentroid": {
          "x": 49,
          "y": 82
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_J",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_J.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,58 L25,53 L45,39 L39,29 L0,45 L0,0 L100,0 L100,100 L58,100 L54,82 L93,70 L92,38 L70,38 L62,20 L49,45 L47,68 L40,80 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 18
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M55,72 L44,78 L50,91 L50,100",
        "meepleCentroid": {
          "x": 46,
          "y": 80
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M0,51 L15,50 L26,43 L37,38",
        "meepleCentroid": {
          "x": 21,
          "y": 46
        }
      },
      {
        "id": "cloister0",
        "type": "CLOISTER",
        "svgPath": "M49,67 L52,43 L61,22 L69,39 L86,41 L92,49 L92,68 L70,77 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 54
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "field0",
      "EAST_RIGHT": "field0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "field0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "road1",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "field0",
        "road1"
      ],
      [
        "field0",
        "cloister0"
      ],
      [
        "field0",
        "road0"
      ],
      [
        "cloister0",
        "road0"
      ]
    ]
  },
  {
    "id": "tb31_K",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_K.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M18,36 L0,0 L100,0 L100,100 L85,85 L63,73 L63,61 Z",
        "commodity": "CLOTH",
        "meepleCentroid": {
          "x": 63,
          "y": 22
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M55,100 L61,72 L100,100 Z",
        "meepleCentroid": {
          "x": 74,
          "y": 85
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L18,38 L37,50 L1,73 L43,88 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 14,
          "y": 50
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M52,50 L41,58 L45,65 L58,76 L51,83 L50,100",
        "meepleCentroid": {
          "x": 55,
          "y": 74
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M4,72 L26,60 L50,72 L29,83 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 71
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field1",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "field1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "field1",
        "garden0"
      ]
    ]
  },
  {
    "id": "tb31_L",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_L.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L84,13 L69,16 L34,81 L0,100 Z",
        "commodity": "CLOTH",
        "hasPennant": false,
        "meepleCentroid": {
          "x": 29,
          "y": 29
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,0 L86,19 L79,41 L88,84 L100,100 Z",
        "meepleCentroid": {
          "x": 87,
          "y": 49
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M43,79 L46,100 L0,100 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 91
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M57,44 L67,21 L80,19 L77,42 L86,84 L100,100 L55,100 L55,79 L62,61 Z",
        "meepleCentroid": {
          "x": 72,
          "y": 75
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,48 L58,61 L50,79 L50,100",
        "meepleCentroid": {
          "x": 51,
          "y": 76
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "city1",
        "field1"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "field1",
        "city0"
      ]
    ]
  },
  {
    "id": "tb31_M",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_M.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L79,32 L59,46 L42,56 L22,66 L15,83 L0,100 Z",
        "commodity": "CLOTH",
        "meepleCentroid": {
          "x": 47,
          "y": 27
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M100,0 L83,28 L82,51 L83,75 L100,100 Z",
        "meepleCentroid": {
          "x": 88,
          "y": 51
        }
      },
      {
        "id": "city2",
        "type": "CITY",
        "svgPath": "M23,82 L50,77 L79,83 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 88
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M22,68 L81,35 L81,76 L19,79 Z",
        "meepleCentroid": {
          "x": 62,
          "y": 63
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city2",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city2"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city1"
      ],
      [
        "field0",
        "city2"
      ]
    ]
  },
  {
    "id": "tb31_N",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_N.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L70,17 L41,18 L19,13 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 8
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M32,28 L64,28 L100,0 L100,100 L76,83 L61,85 L31,82 L0,100 L0,0 Z",
        "commodity": "CLOTH",
        "meepleCentroid": {
          "x": 51,
          "y": 54
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M30,86 L75,85 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 51,
          "y": 86
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,0 L25,16 L68,18 L85,12 L62,27 L30,27 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 23
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city1",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city1",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field0",
      "WEST_CENTER": "city1",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field0"
    },
    "adjacencies": [
      [
        "field1",
        "city0"
      ],
      [
        "field1",
        "city1"
      ],
      [
        "city1",
        "field0"
      ]
    ]
  },
  {
    "id": "tb31_O",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_O.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L100,0 L88,15 L88,62 L100,100 L66,70 L36,72 L19,82 Z",
        "commodity": "CLOTH",
        "hasPennant": false,
        "meepleCentroid": {
          "x": 51,
          "y": 32
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M100,0 L100,44 L91,43 L90,11 Z",
        "meepleCentroid": {
          "x": 92,
          "y": 25
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M89,55 L100,56 L100,100 Z",
        "meepleCentroid": {
          "x": 95,
          "y": 67
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M58,72 L66,71 L100,100 L59,100 Z",
        "meepleCentroid": {
          "x": 70,
          "y": 83
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M31,76 L44,72 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 32,
          "y": 84
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M84,47 L100,50",
        "meepleCentroid": {
          "x": 93,
          "y": 50
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M50,69 L53,77 L50,88 L51,100",
        "meepleCentroid": {
          "x": 50,
          "y": 83
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field3",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "field3"
      ],
      [
        "city0",
        "road1"
      ],
      [
        "road1",
        "field3"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "tb31_P",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_P.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M33,83 L70,83 L100,100 L0,100 Z",
        "hasPennant": false,
        "meepleCentroid": {
          "x": 52,
          "y": 91
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M24,20 L69,20 L100,0 L100,100 L71,74 L33,72 L0,100 L0,0 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 51,
          "y": 45
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L69,17 L23,16 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 14
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M33,74 L69,73 L81,85 L23,84 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 77
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city1",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "city0",
      "WEST_RIGHT": "city1",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "city0",
      "WEST_CENTER": "city1",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "city0"
    },
    "adjacencies": [
      [
        "field1",
        "city0"
      ],
      [
        "city1",
        "field0"
      ],
      [
        "city1",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_Q",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_Q.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M66,21 L100,0 L100,100 L69,72 L34,74 L0,100 L0,0 L28,19 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 51,
          "y": 47
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L28,17 L66,18 L100,0 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 11
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M32,76 L0,100 L100,100 L68,72 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "field1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_R",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_R.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L0,0 L35,29 L66,28 L100,0 L100,100 L75,81 L25,82 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 49,
          "y": 55
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M58,0 L100,0 L65,25 L51,22 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 15
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,86 L76,84 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 72,
          "y": 91
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M22,88 L43,83 L48,100 L0,100 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 91
        }
      },
      {
        "id": "field3",
        "type": "FIELD",
        "svgPath": "M0,0 L46,0 L38,28 L24,20 Z",
        "meepleCentroid": {
          "x": 28,
          "y": 14
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M53,32 L44,23 L55,11 L50,0",
        "meepleCentroid": {
          "x": 47,
          "y": 17
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M54,77 L50,85 L50,93 L53,100",
        "meepleCentroid": {
          "x": 50,
          "y": 91
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field3",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "road0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field3"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road1"
      ],
      [
        "road1",
        "field2"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "road0",
        "field3"
      ],
      [
        "road0",
        "field0"
      ]
    ]
  },
  {
    "id": "tb31_S",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_S.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M65,20 L100,0 L100,100 L67,73 L33,73 L0,100 L0,0 L28,19 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 50,
          "y": 47
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M50,70 L47,80 L53,88 L49,100",
        "meepleCentroid": {
          "x": 51,
          "y": 86
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L100,0 L67,15 L27,16 Z",
        "meepleCentroid": {
          "x": 49,
          "y": 14
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M56,74 L67,73 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 69,
          "y": 85
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M32,75 L43,74 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "field0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "field0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "field0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "road0",
        "field2"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_T",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_T.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L100,100 L71,48 L36,27 L0,0 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 62,
          "y": 19
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M0,0 L70,50 L100,100 L62,100 L66,69 L42,47 L0,36 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 47
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M0,61 L22,64 L42,73 L41,100 L0,100 Z",
        "meepleCentroid": {
          "x": 22,
          "y": 79
        }
      },
      {
        "id": "river0",
        "type": "RIVER",
        "svgPath": "M0,51 L0,45 L45,60 L57,76 L54,100 L47,100 L51,74 L26,58 Z",
        "meepleCentroid": {
          "x": 40,
          "y": 60
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "field1",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "field0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "river0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "river0"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "river0",
        "field0"
      ],
      [
        "river0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_U",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_U.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,100 L37,66 L77,43 L100,0 L0,0 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 44,
          "y": 31
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M81,45 L100,0 L100,44 Z",
        "meepleCentroid": {
          "x": 89,
          "y": 35
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M75,82 L100,69 L100,100 L58,100 L57,86 L51,76 L52,69 Z",
        "meepleCentroid": {
          "x": 87,
          "y": 87
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M31,71 L44,85 L44,100 L0,100 Z",
        "meepleCentroid": {
          "x": 29,
          "y": 85
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M66,46 L76,50 L86,52 L100,50",
        "meepleCentroid": {
          "x": 84,
          "y": 51
        }
      },
      {
        "id": "road1",
        "type": "ROAD",
        "svgPath": "M45,58 L40,75 L52,85 L50,100",
        "meepleCentroid": {
          "x": 49,
          "y": 80
        }
      },
      {
        "id": "garden0",
        "type": "GARDEN",
        "svgPath": "M78,58 L98,69 L75,81 L51,69 Z",
        "meepleCentroid": {
          "x": 75,
          "y": 68
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road1"
    },
    "adjacencies": [
      [
        "road1",
        "field2"
      ],
      [
        "road1",
        "field1"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ],
      [
        "city0",
        "road1"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "garden0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_V",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_V.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L0,100 L34,69 L72,70 L100,100 L100,0 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 53,
          "y": 34
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M56,71 L68,74 L100,100 L56,100 Z",
        "meepleCentroid": {
          "x": 71,
          "y": 88
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M26,81 L45,71 L45,100 L0,100 Z",
        "meepleCentroid": {
          "x": 30,
          "y": 88
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M52,69 L49,80 L51,91 L50,100",
        "meepleCentroid": {
          "x": 52,
          "y": 85
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city0",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field0",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "road0"
    },
    "adjacencies": [
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field0"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_W",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_W.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M100,0 L87,11 L89,58 L100,100 L68,72 L35,71 L0,100 L0,0 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 48,
          "y": 31
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M89,11 L50,50 L100,0 L100,44 L91,42 Z",
        "meepleCentroid": {
          "x": 93,
          "y": 25
        }
      },
      {
        "id": "field1",
        "type": "FIELD",
        "svgPath": "M90,55 L100,56 L100,100 Z",
        "meepleCentroid": {
          "x": 95,
          "y": 67
        }
      },
      {
        "id": "field2",
        "type": "FIELD",
        "svgPath": "M34,72 L66,71 L100,100 L0,100 Z",
        "meepleCentroid": {
          "x": 50,
          "y": 81
        }
      },
      {
        "id": "road0",
        "type": "ROAD",
        "svgPath": "M83,47 L89,47 L95,49 L100,51",
        "meepleCentroid": {
          "x": 94,
          "y": 50
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "field0",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "field1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "field2",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "road0",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "field2",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "field2"
    },
    "adjacencies": [
      [
        "city0",
        "field0"
      ],
      [
        "city0",
        "road0"
      ],
      [
        "city0",
        "field1"
      ],
      [
        "city0",
        "field2"
      ],
      [
        "road0",
        "field0"
      ],
      [
        "road0",
        "field1"
      ]
    ]
  },
  {
    "id": "tb31_X",
    "imageUrl": "/images/TradersAndBuilders_C31/Traders_And_Builders_C31_Tile_X.jpg",
    "count": 1,
    "expansionId": "traders-builders-c31",
    "version": "C3.1",
    "segments": [
      {
        "id": "city0",
        "type": "CITY",
        "svgPath": "M0,0 L100,0 L48,42 L32,49 L22,66 L0,100 Z",
        "commodity": "WINE",
        "meepleCentroid": {
          "x": 41,
          "y": 18
        }
      },
      {
        "id": "city1",
        "type": "CITY",
        "svgPath": "M78,52 L72,43 L100,0 L100,100 L0,100 L22,83 L42,73 L61,65 Z",
        "meepleCentroid": {
          "x": 77,
          "y": 77
        }
      },
      {
        "id": "field0",
        "type": "FIELD",
        "svgPath": "M32,50 L77,22 L72,53 L0,100 Z",
        "meepleCentroid": {
          "x": 52,
          "y": 51
        }
      }
    ],
    "edgePositionToSegment": {
      "EAST_LEFT": "city1",
      "WEST_LEFT": "city0",
      "EAST_RIGHT": "city1",
      "NORTH_LEFT": "city0",
      "SOUTH_LEFT": "city1",
      "WEST_RIGHT": "city0",
      "EAST_CENTER": "city1",
      "NORTH_RIGHT": "city0",
      "SOUTH_RIGHT": "city1",
      "WEST_CENTER": "city0",
      "NORTH_CENTER": "city0",
      "SOUTH_CENTER": "city1"
    },
    "adjacencies": [
      [
        "field0",
        "city0"
      ],
      [
        "field0",
        "city1"
      ]
    ]
  }
]
